services:
  artichat:
    build:
      context: .
      dockerfile: Dockerfile
    image: artichat:${ARTICHAT_DOCKER_TAG-main}
    container_name: artichat
    volumes:
      - artichat-data:/app/backend/data
    ports:
      - ${ARTICHAT_PORT-3000}:8080
    environment:
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  artichat-data:
    name: artichat_data
